name: dynamic_form_kit
description: A reusable package for rendering dynamic forms from JSON.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 1. Add any packages your widgets need
  intl: ^0.20.2
  multi_select_flutter: ^4.1.3 # Add this for your MultiSelectWrapper
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  syncfusion_flutter_datepicker: ^31.2.5
  syncfusion_flutter_charts: ^31.2.12
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_gauges: ^31.2.12
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0